openapi: 3.1.0
info:
  title: AutoAI Europe Backend
  version: 1.0.0
servers:
  - url: https://example.com
paths:
  /:
    get:
      summary: Health check
      responses:
        "200":
          description: OK
