openapi: 3.1.0
info:
  title: AutoAI Europe Backend
  version: 1.0.0

servers:
  - url: https://autoai-europe.onrender.com

paths:

  /:
    get:
      operationId: healthCheck
      summary: Health check endpoint
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  service:
                    type: string

  /vin/scan:
    post:
      operationId: vinScan
      summary: EU VIN decoder (basic)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                vin:
                  type: string
      responses:
        "200":
          description: VIN decode result
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  vin:
                    type: string
                  decoded:
                    type: object

  /dtc/lookup:
    post:
      operationId: dtcLookup
      summary: EU DTC lookup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
      responses:
        "200":
          description: DTC lookup result
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object

  /symptom/search:
    post:
      operationId: symptomSearch
      summary: Search symptoms from EU database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        "200":
          description: Symptom search result
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object

  /diagnostic/search:
    post:
      operationId: diagnosticSearch
      summary: Multi-source EU diagnostic search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                vin: { type: string }
                model: { type: string }
                engine_code: { type: string }
                dtc_code: { type: string }
                symptom_text: { type: string }
      responses:
        "200":
          description: Combined diagnostic result
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object

  /search_parts:
    post:
      operationId: partsSearch
      summary: EU aftermarket parts search (Bosch, Valeo, Hella)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                vin: { type: string }
                query: { type: string }
      responses:
        "200":
          description: Parts search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object

  /documents/presign:
    post:
      operationId: presignUpload
      summary: Generate presigned URL for OEM document upload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filename: { type: string }
      responses:
        "200":
          description: Presign result
          content:
            application/json:
              schema:
                type: object
                properties:
                  url: { type: string }
                  key: { type: string }

  /documents:
    post:
      operationId: createDocument
      summary: Store metadata for an uploaded OEM document
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title: { type: string }
                source_type: { type: string }
                system: { type: string }
                blob_key: { type: string }
      responses:
        "200":
          description: Document stored
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: { type: string }
                  status: { type: string }
