openapi: 3.1.0
info:
  title: AutoAI Europe Backend
  version: 1.0.0

servers:
  - url: https://autoai-europe.onrender.com

paths:

  /:
    get:
      operationId: healthCheck
      summary: Health check
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  service:
                    type: string
  /vin/scan:
    post:
      operationId: vinScan
      summary: Basic EU VIN decoder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                vin:
                  type: string
                  example: "WVWZZZ1KZ6W123456"
      responses:
        "200":
          description: VIN decode result
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  vin:
                    type: string
                  decoded:
                    type: object
  /dtc/lookup:
    post:
      operationId: dtcLookup
      summary: EU diagnostic trouble code lookup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  example: "P2015"
      responses:
        "200":
          description: EU DTC lookup result
          content:
            application/json:
              schema:
                type: object

