openapi: 3.1.0
info:
  title: AutoAI Europe Backend
  version: 1.0.0

servers:
  - url: https://autoai-europe.onrender.com

paths:

  /:
    get:
      operationId: healthCheck
      summary: Health check
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  service:
                    type: string

